import * as fs from 'fs';
import * as path from 'path';
import type {
  BranchChallengeLevel1,
  BranchChallengeLevel2,
  BranchChallengeLevel3,
  BranchChallengeLevel4,
} from '../lib/branch-challenge-types';
import {
  generateBranchChallengesLevel1,
  generateBranchChallengesLevel2,
  generateBranchChallengesLevel3,
  generateBranchChallengesLevel4,
} from '../lib/branch-level-config';

const CHALLENGES_PER_LEVEL = 30;

function formatLevel1(ch: BranchChallengeLevel1): string {
  const branchesStr = `["${ch.branches[0]}", "${ch.branches[1]}", "${ch.branches[2]}"]`;
  const idx = ch.correctBranchIndex;
  return `    { level: 1, branches: ${branchesStr}, correctBranchIndex: ${idx}, validate: (i) => i[0] === ${idx} }`;
}

function formatLevel2(ch: BranchChallengeLevel2): string {
  const candidatesStr = `["${ch.candidateBranches[0]}", "${ch.candidateBranches[1]}", "${ch.candidateBranches[2]}"]`;
  const idx = ch.correctCandidateIndex;
  return `    { level: 2, knownBranch: "${ch.knownBranch}", knownBranchPosition: "${ch.knownBranchPosition}", candidateBranches: ${candidatesStr}, correctCandidateIndex: ${idx}, validate: (i) => i[0] === ${idx} }`;
}

function formatLevel3(ch: BranchChallengeLevel3): string {
  const outputsStr = ch.candidateOutputs
    .map((arr) => `[${arr.join(',')}]`)
    .join(', ');
  const idx = ch.correctOutputIndex;
  return `    { level: 3, branchA: "${ch.branchA}", branchB: "${ch.branchB}", candidateOutputs: [${outputsStr}], correctOutputIndex: ${idx}, validate: (i) => i[0] === ${idx} }`;
}

function formatLevel4(ch: BranchChallengeLevel4): string {
  const pairsStr = ch.candidatePairs
    .map((p) => `["${p[0]}","${p[1]}"]`)
    .join(', ');
  const idx = ch.correctPairIndex;
  return `    { level: 4, candidatePairs: [${pairsStr}], correctPairIndex: ${idx}, validate: (i) => i[0] === ${idx} }`;
}

function main() {
  const level1 = generateBranchChallengesLevel1(CHALLENGES_PER_LEVEL);
  const level2 = generateBranchChallengesLevel2(CHALLENGES_PER_LEVEL);
  const level3 = generateBranchChallengesLevel3(CHALLENGES_PER_LEVEL);
  const level4 = generateBranchChallengesLevel4(CHALLENGES_PER_LEVEL);

  const lines: string[] = [
    "// Auto-generated by scripts/generate-branch-challenges.ts",
    "import type { BranchChallenge } from './branch-challenge-types';",
    "",
    "export const BRANCH_CHALLENGE_BANK: Record<1 | 2 | 3 | 4, BranchChallenge[]> = {",
    "  1: [",
    ...level1.map((ch) => formatLevel1(ch) + ","),
    "  ],",
    "  2: [",
    ...level2.map((ch) => formatLevel2(ch) + ","),
    "  ],",
    "  3: [",
    ...level3.map((ch) => formatLevel3(ch) + ","),
    "  ],",
    "  4: [",
    ...level4.map((ch) => formatLevel4(ch) + ","),
    "  ],",
    "};",
  ];

  const outputPath = path.join(__dirname, "..", "lib", "branch-challenges.generated.ts");
  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
  console.log(
    `Generated ${outputPath} with ${level1.length} L1 + ${level2.length} L2 + ${level3.length} L3 + ${level4.length} L4 challenges`
  );
}

main();
