import * as fs from 'fs';
import * as path from 'path';
import type {
  BranchChallengeLevel1,
  BranchChallengeLevel2,
  BranchChallengeLevel3,
  BranchChallengeLevel4,
} from '../lib/branch-challenge-types';
import {
  generateBranchChallengesLevel1,
  generateBranchChallengesLevel2,
  generateBranchChallengesLevel3,
  generateBranchChallengesLevel4,
} from '../lib/branch-level-config';

const CHALLENGES_PER_LEVEL = 30;

function formatLevel1(ch: BranchChallengeLevel1): string {
  const branchesStr = `["${ch.branches[0]}", "${ch.branches[1]}", "${ch.branches[2]}"]`;
  const idx = ch.correctBranchIndex;
  return `    { level: 1, branches: ${branchesStr}, correctBranchIndex: ${idx}, validate: (i) => i[0] === ${idx} }`;
}

function formatLevel2(ch: BranchChallengeLevel2): string {
  const candidatesStr = `["${ch.candidateBranches[0]}", "${ch.candidateBranches[1]}", "${ch.candidateBranches[2]}"]`;
  const idx = ch.correctCandidateIndex;
  return `    { level: 2, knownBranch: "${ch.knownBranch}", knownBranchPosition: "${ch.knownBranchPosition}", candidateBranches: ${candidatesStr}, correctCandidateIndex: ${idx}, validate: (i) => i[0] === ${idx} }`;
}

function formatLevel3(ch: BranchChallengeLevel3): string {
  const a = ch.branchA === null ? 'null' : `"${ch.branchA}"`;
  const b = ch.branchB === null ? 'null' : `"${ch.branchB}"`;
  const c = ch.branchC === null ? 'null' : `"${ch.branchC}"`;
  const candidatesStr = `["${ch.candidateBranches[0]}", "${ch.candidateBranches[1]}", "${ch.candidateBranches[2]}"]`;
  const idx = ch.correctCandidateIndex;
  return `    { level: 3, branchA: ${a}, branchB: ${b}, branchC: ${c}, candidateBranches: ${candidatesStr}, correctCandidateIndex: ${idx}, validate: (i) => i[0] === ${idx} }`;
}

function formatLevel4(ch: BranchChallengeLevel4): string {
  const aStr = `["${ch.candidateBranchesA[0]}", "${ch.candidateBranchesA[1]}", "${ch.candidateBranchesA[2]}"]`;
  const bStr = `["${ch.candidateBranchesB[0]}", "${ch.candidateBranchesB[1]}", "${ch.candidateBranchesB[2]}"]`;
  return `    { level: 4, candidateBranchesA: ${aStr}, candidateBranchesB: ${bStr}, correctAIndex: ${ch.correctAIndex}, correctBIndex: ${ch.correctBIndex}, validate: (i) => i[0] === ${ch.correctAIndex} && i[1] === ${ch.correctBIndex} }`;
}

function shuffle<T>(arr: T[]): T[] {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

function main() {
  const singleStage = generateBranchChallengesLevel1(CHALLENGES_PER_LEVEL);
  const serialDeduction = generateBranchChallengesLevel2(CHALLENGES_PER_LEVEL);
  const mergedLevel1 = shuffle([...singleStage, ...serialDeduction]);
  const level2 = generateBranchChallengesLevel3(CHALLENGES_PER_LEVEL);
  const level3 = generateBranchChallengesLevel4(CHALLENGES_PER_LEVEL);

  const formatChallenge = (ch: { level: number }) => {
    if (ch.level === 1) return formatLevel1(ch as BranchChallengeLevel1);
    if (ch.level === 2) return formatLevel2(ch as BranchChallengeLevel2);
    if (ch.level === 3) return formatLevel3(ch as BranchChallengeLevel3);
    return formatLevel4(ch as BranchChallengeLevel4);
  };

  const lines: string[] = [
    "// Auto-generated by scripts/generate-branch-challenges.ts",
    "import type { BranchChallenge } from './branch-challenge-types';",
    "",
    "export const BRANCH_CHALLENGE_BANK: Record<1 | 2 | 3, BranchChallenge[]> = {",
    "  1: [",
    ...mergedLevel1.map((ch) => formatChallenge(ch) + ","),
    "  ],",
    "  2: [",
    ...level2.map((ch) => formatLevel3(ch) + ","),
    "  ],",
    "  3: [",
    ...level3.map((ch) => formatLevel4(ch) + ","),
    "  ],",
    "};",
  ];

  const outputPath = path.join(__dirname, "..", "lib", "branch-challenges.generated.ts");
  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
  console.log(
    `Generated ${outputPath}: L1 merged ${singleStage.length}+${serialDeduction.length}, L2 ${level2.length}, L3 ${level3.length}`
  );
}

main();
