import * as fs from 'fs';
import * as path from 'path';
import { LEVEL_POOLS, pickRandom } from '../lib/level-config';

const CHALLENGES_PER_LEVEL = 30;
const MAX_ATTEMPTS = 300;

function generateLevel(level: number): Array<{ formula: string; validateSource: string }> {
  const pool = LEVEL_POOLS.find((p) => p.level === level);
  if (!pool || pool.generators.length === 0) return [];

  const seen = new Set<string>();
  const challenges: Array<{ formula: string; validateSource: string }> = [];

  for (let attempt = 0; attempt < MAX_ATTEMPTS && challenges.length < CHALLENGES_PER_LEVEL; attempt++) {
    const generator = pickRandom(pool.generators);
    const result = generator();
    if (!result) continue;
    if (seen.has(result.formula)) continue;
    seen.add(result.formula);
    challenges.push(result);
  }

  return challenges;
}

function formatChallenge(ch: { formula: string; validateSource: string }): string {
  const formulaEscaped = ch.formula.replace(/"/g, '\\"');
  return `    { formula: "${formulaEscaped}", validate: ${ch.validateSource} }`;
}

function main() {
  const bank: Record<number, Array<{ formula: string; validateSource: string }>> = {};

  for (const pool of LEVEL_POOLS) {
    const challenges = generateLevel(pool.level);
    bank[pool.level] = challenges;
  }

  const levels = Object.keys(bank)
    .map(Number)
    .sort((a, b) => a - b);

  const lines: string[] = [
    '// Auto-generated by scripts/generate-challenges.ts',
    "import type { Challenge } from './challenge-types';",
    '',
    'export const CHALLENGE_BANK: Record<number, Challenge[]> = {',
  ];

  for (const level of levels) {
    const challenges = bank[level];
    lines.push(`  ${level}: [`);
    lines.push(...challenges.map((ch) => formatChallenge(ch) + ','));
    lines.push('  ],');
  }

  lines.push('};');

  const outputPath = path.join(__dirname, '..', 'lib', 'challenges.generated.ts');
  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');
  console.log(`Generated ${outputPath} with ${levels.map((l) => bank[l].length).join(', ')} challenges per level`);
}

main();
